/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bsw;

import com.google.api.client.auth.oauth2.Credential;
import com.google.api.client.extensions.java6.auth.oauth2.AuthorizationCodeInstalledApp;
import com.google.api.client.extensions.jetty.auth.oauth2.LocalServerReceiver;
import com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow;
import com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.JsonFactory;
import com.google.api.client.json.jackson2.JacksonFactory;
import com.google.api.client.util.store.FileDataStoreFactory;
import com.google.api.services.sheets.v4.SheetsScopes;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.security.GeneralSecurityException;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws IOException, GeneralSecurityException {
//        String sheetName = "Apna Ludo Final";
//        int startRow = 131;
//        int endRow = 132;

        Scanner sc= new Scanner(System.in);

        System.out.println("Select Project:");
        System.out.println("1. Ludo Superstar");
        System.out.println("2. Apna Ludo");

        int project = sc.nextInt();

        System.out.println("Start Row(Inclusive) <space> End Row(Inclusive)");
        int start = Integer.parseInt(sc.next());
        int end = Integer.parseInt(sc.next());

        if (start > 0 && end >= start){
            GoogleSheetsService.readFromSpreadSheet(project,start,end);
        }

    }
}
