/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bsw;

import com.bsw.ui.MyFrame;
import com.google.api.client.auth.oauth2.Credential;
import com.google.api.client.extensions.java6.auth.oauth2.AuthorizationCodeInstalledApp;
import com.google.api.client.extensions.jetty.auth.oauth2.LocalServerReceiver;
import com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow;
import com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.JsonFactory;
import com.google.api.client.json.jackson2.JacksonFactory;
import com.google.api.client.util.store.FileDataStoreFactory;
import com.google.api.services.sheets.v4.SheetsScopes;

import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.security.GeneralSecurityException;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;
import java.util.regex.Pattern;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class App {

    public static MyFrame myFrame;

    public static void main(String[] args) {
        myFrame = new MyFrame();

//        Pattern p = Pattern.compile("<!--[\\s\\S].*?-->");

        String str = "Invalid String at default  Row:1266  <string name=\"challange_sent_msg\">Challenge Sent. Waiting for %s to accept it.</string>";
//        System.out.println((str.substring(str.indexOf("</string>")+9).trim()));
//        System.out.println(p.matcher(str).replaceAll("").trim());
    }

    public static void writeLogs(String str) {
        myFrame.writeOutput(str);
    }
}
